In [1]:
import pandas as pd
import json

In [2]:
file = open('5.1.5 Tweets.json','r',encoding = 'utf-8')
Text = ''
for line in file :
    Text = line

In [3]:
Text

'[{"user_id":"2832795611","status_id":"1408758089822703616","created_at":"2021-06-26 12:04:36","screen_name":"amrnaga74","text":"❌باقي 96ساعة\\nإما نستقبل التهاني\\nبعودة جيش مصر لحماية شعبه\\nأو نتلقى التعازي\\n#سد_النهضة\\n#الجيش_المصري","source":"Twitter for Android","display_text_width":120,"is_quote":false,"is_retweet":true,"favorite_count":0,"retweet_count":20,"hashtags":["سد_النهضة","الجيش_المصري"],"symbols":[null],"urls_url":[null],"urls_t.co":[null],"urls_expanded_url":[null],"media_url":[null],"media_t.co":[null],"media_expanded_url":[null],"media_type":[null],"ext_media_url":[null],"ext_media_t.co":[null],"ext_media_expanded_url":[null],"mentions_user_id":["352489322"],"mentions_screen_name":["haythamabokhal1"],"lang":"ar","retweet_status_id":"1408731082913193985","retweet_text":"❌باقي 96ساعة\\nإما نستقبل التهاني\\nبعودة جيش مصر لحماية شعبه\\nأو نتلقى التعازي\\n#سد_النهضة\\n#الجيش_المصري","retweet_created_at":"2021-06-26 10:17:17","retweet_source":"Twitter for Android","retweet_favorite_count":144,"retweet_retweet_count":20,"retweet_user_id":"352489322","retweet_screen_name":"haythamabokhal1","retweet_name":"Haytham Abokhalil هيثم أبوخليل","retweet_followers_count":571403,"retweet_friends_count":781,"retweet_statuses_count":42915,"retweet_location":"Alexandria,Egypt","retweet_description":"\u200f\u200fTV presenter& Human Rights Activist إعلامي وناشط حقوقي وسياسي مصري ـــــــــــــــ باشتغل واكتب علشان أرجع مصر من إللي خاطفينها ومستعد أدفع الفدية حياتي","retweet_verified":true,"geo_coords":["NA","NA"],"coords_coords":["NA","NA"],"bbox_coords":["NA","NA","NA","NA","NA","NA","NA","NA"],"status_url":"https://twitter.com/amrnaga74/status/1408758089822703616","name":"عمرو نجا","location":"","description":"","protected":false,"followers_count":152,"friends_count":430,"listed_count":0,"statuses_count":17995,"favourites_count":24044,"account_created_at":"2014-10-15 21:58:35","verified":false,"profile_banner_url":"https://pbs.twimg.com/profile_banners/2832795611/1444404303","profile_background_url":"http://abs.twimg.com/images/themes/theme1/bg.png","profile_image_url":"http://pbs.twimg.com/profile_images/524733022692966400/qE_Vb7qp_normal.jpeg"},{"user_id":"1250468867996110848","status_id":"1408757945962225665","created_at":"2021-06-26 12:04:02","screen_name":"ahlmasrnews0","text":"#عاجل| بعد فشل مفاوضات سد النهضة.. وزير الخارجية يوضح حقيقة ما يثار حول شراء مصر المياه من إثيوبيا\\n\\nالتفاصيل.. https://t.co/CqxYU3Pvoi https://t.co/fsOA3Mgupj","source":"TweetDeck","display_text_width":134,"is_quote":false,"is_retweet":false,"favorite_count":0,"retweet_count":0,"hashtags":["عاجل"],"symbols":[null],"urls_url":["bit.ly/3jnZJHk"],"urls_t.co":["https://t.co/CqxYU3Pvoi"],"urls_expanded_url":["https://bit.ly/3jnZJHk"],"media_url":["http://pbs.twimg.com/media/E4zp4czXoAU4rZZ.jpg"],"media_t.co":["https://t.co/fsOA3Mgupj"],"media_expanded_url":["https://twitter.com/ahlmasrnews0/status/1408757945962225665/photo/1"],"media_type":["photo"],"ext_media_url":["http://pbs.twimg.com/media/E4zp4czXoAU4rZZ.jpg"],"ext_media_t.co":["https://t.co/fsOA3Mgupj"],"ext_media_expanded_url":["https://twitter.com/ahlmasrnews0/status/1408757945962225665/photo/1"],"mentions_user_id":[null],"mentions_screen_name":[null],"lang":"ar","geo_coords":["NA","NA"],"coords_coords":["NA","NA"],"bbox_coords":["NA","NA","NA","NA","NA","NA","NA","NA"],"status_url":"https://twitter.com/ahlmasrnews0/status/1408757945962225665","name":"جريدة أهل مصر","location":"cairo","description":"موقع إخبارى يختص بنشر الأخبار المحلية والإقليمية والعالمية في شتى المجالات المختلفة على مدار الساعة","url":"https://t.co/CQO84TklH4","protected":false,"followers_count":3117,"friends_count":0,"listed_count":5,"statuses_count":28662,"favourites_count":1,"account_created_at":"2020-04-15 17:00:11","verified":false,"profile_url":"https://t.co/CQO84TklH4","profile_expanded_url":"https://www.ahlmasrnews.com/","profile_banner_url":"https://pbs.twimg.com/profile_banners/1250468867996110848/1621334982","profile_image_url":"http://pbs.twimg.com/profile_images/1394605956760317957/PXqLiFR0_normal.png"},{"user_id":"915574061182398465","status_id":"1408757770057363456","created_at":"2021-06-26 12:03:20","screen_name":"Alyameny6","text":"وزير الخارجية المصري: تصريحات #اثيوبيا عن عمل عسكري ضد #سد_النهضة استفزازية بهدف التهرب من الالتزامات ورفض توقيع اتفاق قانوني عادل وملزم\\n#مصر لديها القدرة ولن تتهاون في الدفاع عن مصالح شعبها اذا ما وقع الضرر ولكننا نتمسك بالحلول الدبلوماسية والتفاوضية واللجوء الى الاليات الدولية","source":"Twitter for Android","display_text_width":140,"is_quote":false,"is_retweet":true,"favorite_count":0,"retweet_count":3,"hashtags":["اثيوبيا","سد_النهضة"],"symbols":[null],"urls_url":[null],"urls_t.co":[null],"urls_expanded_url":[null],"media_url":[null],"media_t.co":[null],"media_expanded_url":[null],"media_type":[null],"ext_media_url":[null],"ext_media_t.co":[null],"ext_media_expanded_url":[null],"mentions_user_id":["49932833"],"mentions_screen_name":["fayednet"],"lang":"ar","retweet_status_id":"1408756683267006464","retweet_text":"وزير الخارجية المصري: تصريحات #اثيوبيا عن عمل عسكري ضد #سد_النهضة استفزازية بهدف التهرب من الالتزامات ورفض توقيع اتفاق قانوني عادل وملزم\\n#مصر لديها القدرة ولن تتهاون في الدفاع عن مصالح شعبها اذا ما وقع الضرر ولكننا نتمسك بالحلول الدبلوماسية والتفاوضية واللجوء الى الاليات الدولية","retweet_created_at":"2021-06-26 11:59:01","retweet_source":"Twitter for iPhone","retweet_favorite_count":16,"retweet_retweet_count":3,"retweet_user_id":"49932833","retweet_screen_name":"fayednet","retweet_name":"Abdelfattah Fayed عبدالفتاح فايد","retweet_followers_count":78088,"retweet_friends_count":1109,"retweet_statuses_count":2689,"retweet_location":"مصر","retweet_description":"Aljazeera Media Network محرر الشؤون المصرية في قناة الجزيرة","retweet_verified":false,"geo_coords":["NA","NA"],"coords_coords":["NA","NA"],"bbox_coords":["NA","NA","NA","NA","NA","NA","NA","NA"],"status_url":"https://twitter.com/Alyameny6/status/1408757770057363456","name":"أمير اليماني","location":"Yemen","description":"\u200f\u200f\u200f\u200f\u200f\u200fمهندس. محب لصداقة والتواصل مع الجميع","protected":false,"followers_count":1166,"friends_count":474,"listed_count":1,"statuses_count":118817,"favourites_count":233822,"account_created_at":"2017-10-04 13:47:21","verified":false,"profile_banner_url":"https://pbs.twimg.com/profile_banners/915574061182398465/1579892487","profile_image_url":"http://pbs.twimg.com/profile_images/1400280208796753922/0KjqV3Qc_normal.jpg"},{"user_id":"1159842713925111809","status_id":"1408757417639301123","created_at":"2021-06-26 12:01:56","screen_name":"bG0W6NTw6Y1ljNo","text":"وزير الخارجية المصري: تصريحات #اثيوبيا عن عمل عسكري ضد #سد_النهضة استفزازية بهدف التهرب من الالتزامات ورفض توقيع اتفاق قانوني عادل وملزم\\n#مصر لديها القدرة ولن تتهاون في الدفاع عن مصالح شعبها اذا ما وقع الضرر ولكننا نتمسك بالحلول الدبلوماسية والتفاوضية واللجوء الى الاليات الدولية","source":"Twitter for Android","display_text_width":140,"is_quote":false,"is_retweet":true,"favorite_count":0,"retweet_count":3,"hashtags":["اثيوبيا","سد_النهضة"],"symbols":[null],"urls_url":[null],"urls_t.co":[null],"urls_expanded_url":[null],"media_url":[null],"media_t.co":[null],"media_expanded_url":[null],"media_type":[null],"ext_media_url":[null],"ext_media_t.co":[null],"ext_media_expanded_url":[null],"mentions_user_id":["49932833"],"mentions_screen_name":["fayednet"],"lang":"ar","retweet_status_id":"1408756683267006464","retweet_text":"وزير الخارجية المصري: تصريحات #اثيوبيا عن عمل عسكري ضد #سد_النهضة استفزازية بهدف التهرب من الالتزامات ورفض توقيع اتفاق قانوني عادل وملزم\\n#مصر لديها القدرة ولن تتهاون في الدفاع عن مصالح شعبها اذا ما وقع الضرر ولكننا نتمسك بالحلول الدبلوماسية والتفاوضية واللجوء الى الاليات الدولية","retweet_created_at":"2021-06-26 11:59:01","retweet_source":"Twitter for iPhone","retweet_favorite_count":16,"retweet_retweet_count":3,"retweet_user_id":"49932833","retweet_screen_name":"fayednet","retweet_name":"Abdelfattah Fayed عبدالفتاح فايد","retweet_followers_count":78088,"retweet_friends_count":1109,"retweet_statuses_count":2689,"retweet_location":"مصر","retweet_description":"Aljazeera Media Network محرر الشؤون المصرية في قناة الجزيرة","retweet_verified":false,"geo_coords":["NA","NA"],"coords_coords":["NA","NA"],"bbox_coords":["NA","NA","NA","NA","NA","NA","NA","NA"],"status_url":"https://twitter.com/bG0W6NTw6Y1ljNo/status/1408757417639301123","name":"سليمان اليماني","location":"Yemen","description":"\u200f\u200f\u200f\u200f\u200fيقال ان الانسان يفارق الحياة ثلاث مرات الاولى حين يفقد برائتة والثانيه حين يفقد سذاجتة اما الثالثة فهي بمفارقة الحياة نفسها... !","protected":false,"followers_count":477,"friends_count":672,"listed_count":0,"statuses_count":49175,"favourites_count":71355,"account_created_at":"2019-08-09 15:03:46","verified":false,"profile_banner_url":"https://pbs.twimg.com/profile_banners/1159842713925111809/1572510225","profile_image_url":"http://pbs.twimg.com/profile_images/1286777605174235137/cJbFoc72_normal.jpg"},{"user_id":"2399339752","status_id":"1408757131713581056","created_at":"2021-06-26 12:00:48","screen_name":"ossamamh1","text":"اشتري مني، التوقيت الوحيد المظبوط لحل أزمة سد النهضة هو التوقيت الذي ستقرره مصر للحل (بأي صورة من الصور)، شكرا ونرجو ان نكون قد امتعناكم","source":"Twitter for iPhone","display_text_width":139,"is_quote":false,"is_retweet":true,"favorite_count":0,"retweet_count":5,"hashtags":[null],"symbols":[null],"urls_url":[null],"urls_t.co":[null],"urls_expanded_url":[null],"media_url":[null],"media_t.co":[null],"media_expanded_url":[null],"media_type":[null],"ext_media_url":[null],"ext_media_t.co":[null],"ext_media_expanded_url":[null],"mentions_user_id":["2460756808"],"mentions_screen_name":["kokoshylock66"],"lang":"ar","retweet_status_id":"1408749645833121792","retweet_text":"اشتري مني، التوقيت الوحيد المظبوط لحل أزمة سد النهضة هو التوقيت الذي ستقرره مصر للحل (بأي صورة من الصور)، شكرا ونرجو ان نكون قد امتعناكم","retweet_created_at":"2021-06-26 11:31:03","retweet_source":"Twitter for Android","retweet_favorite_count":15,"retweet_retweet_count":5,"retweet_user_id":"2460756808","retweet_screen_name":"kokoshylock66","retweet_name":"Ronin🇪🇬🇪🇬","retweet_followers_count":1812,"retweet_friends_count":2238,"retweet_statuses_count":55185,"retweet_location":"Cairo ","retweet_description":"Where Demons Fear to Tread","retweet_verified":false,"geo_coords":["NA","NA"],"coords_coords":["NA","NA"],"bbox_coords":["NA","NA","NA","NA","NA","NA","NA","NA"],"status_url":"https://twitter.com/ossamamh1/status/1408757131713581056","name":"🇪🇬osama #الانصاري","location":"Aswan","description":"ربي اجعلني مقيم الصلاة ومن ذريتي ربنا وتقبل دعاء","protected":false,"followers_count":2256,"friends_count":441,"listed_count":15,"statuses_count":199890,"favourites_count":91090,"account_created_at":"2014-03-10 11:51:43","verified":false,"profile_banner_url":"https://pbs.twimg.com/profile_banners/2399339752/1590083269","profile_background_url":"http://abs.twimg.com/images/themes/theme1/bg.png","profile_image_url":"http://pbs.twimg.com/profile_images/1379392840518733830/8TPGC4e9_normal.jpg"},{"user_id":"1341772559784796161","status_id":"1408757018991775747","created_at":"2021-06-26 12:00:21","screen_name":"Menap98642","text":"قالك اثيوبيا جاهزة للحل العسكرى فى قضية سد النهضة هى هى هى هى 😂😂😂\\n\\nيا جماعة كفاية كوميديا ده انتوا مش باقى فى جيشكم حد كلهم اسرى عند قوات التيغراى 😁 https://t.co/OGd8cqsOM4","source":"Twitter for Android","display_text_width":139,"is_quote":false,"is_retweet":true,"favorite_count":0,"retweet_count":8,"hashtags":[null],"symbols":[null],"urls_url":[null],"urls_t.co":[null],"urls_expanded_url":[null],"media_url":[null],"media_t.co":[null],"media_expanded_url":[null],"media_type":[null],"ext_media_url":[null],"ext_media_t.co":[null],"ext_media_expanded_url":[null],"mentions_user_id":["344677786"],"mentions_screen_name":["santafaaa"],"lang":"ar","retweet_status_id":"1408735101287079938","retweet_text":"قالك اثيوبيا جاهزة للحل العسكرى فى قضية سد النهضة هى هى هى هى 😂😂😂\\n\\nيا جماعة كفاية كوميديا ده انتوا مش باقى فى جيشكم حد كلهم اسرى عند قوات التيغراى 😁 https://t.co/OGd8cqsOM4","retweet_created_at":"2021-06-26 10:33:15","retweet_source":"Twitter for iPhone","retweet_favorite_count":28,"retweet_retweet_count":8,"retweet_user_id":"344677786","retweet_screen_name":"santafaaa","retweet_name":"ahmed mostafa","retweet_followers_count":6540,"retweet_friends_count":4671,"retweet_statuses_count":8994,"retweet_location":"Egypt","retweet_description":"مصرى أعشق تراب بلدى (مصر أولًا🇪🇬) / قناة اليوتيوب👇 https://t.co/znocfPp5Qn","retweet_verified":false,"geo_coords":["NA","NA"],"coords_coords":["NA","NA"],"bbox_coords":["NA","NA","NA","NA","NA","NA","NA","NA"],"status_url":"https://twitter.com/Menap98642/status/1408757018991775747","name":"Menapop💪🇪🇬( الشنتوحه)😂😎👊","location":"الأسكندرية, مصر","description":"\u200fالشنتوحه مصري🇪🇬💪والشنتوحه اسلوبي","protected":false,"followers_count":14044,"friends_count":4341,"listed_count":6,"statuses_count":3541,"favourites_count":5497,"account_created_at":"2020-12-23 15:48:52","verified":false,"profile_image_url":"http://pbs.twimg.com/profile_images/1341773094789255168/-Vh6J4L0_normal.jpg"},{"user_id":"1326981402","status_id":"1408756824162111489","created_at":"2021-06-26 11:59:34","screen_name":"23Sherif","text":"❌باقي 96ساعة\\nإما نستقبل التهاني\\nبعودة جيش مصر لحماية شعبه\\nأو نتلقى التعازي\\n#سد_النهضة\\n#الجيش_المصري","source":"Twitter for Android","display_text_width":120,"is_quote":false,"is_retweet":true,"favorite_count":0,"retweet_count":20,"hashtags":["سد_النهضة","الجيش_المصري"],"symbols":[null],"urls_url":[null],"urls_t.co":[null],"urls_expanded_url":[null],"media_url":[null],"media_t.co":[null],"media_expanded_url":[null],"media_type":[null],"ext_media_url":[null],"ext_media_t.co":[null],"ext_media_expanded_url":[null],"mentions_user_id":["352489322"],"mentions_screen_name":["haythamabokhal1"],"lang":"ar","retweet_status_id":"1408731082913193985","retweet_text":"❌باقي 96ساعة\\nإما نستقبل التهاني\\nبعودة جيش مصر لحماية شعبه\\nأو نتلقى التعازي\\n#سد_النهضة\\n#الجيش_المصري","retweet_created_at":"2021-06-26 10:17:17","retweet_source":"Twitter for Android","retweet_favorite_count":144,"retweet_retweet_count":20,"retweet_user_id":"352489322","retweet_screen_name":"haythamabokhal1","retweet_name":"Haytham Abokhalil هيثم أبوخليل","retweet_followers_count":571403,"retweet_friends_count":781,"retweet_statuses_count":42915,"retweet_location":"Alexandria,Egypt","retweet_description":"\u200f\u200fTV presenter& Human Rights Activist إعلامي وناشط حقوقي وسياسي مصري ـــــــــــــــ باشتغل واكتب علشان أرجع مصر من إللي خاطفينها ومستعد أدفع الفدية حياتي","retweet_verified":true,"geo_coords":["NA","NA"],"coords_coords":["NA","NA"],"bbox_coords":["NA","NA","NA","NA","NA","NA","NA","NA"],"status_url":"https://twitter.com/23Sherif/status/1408756824162111489","name":"sherif","location":"المملكة العربية السعودية","description":"","protected":false,"followers_count":1959,"friends_count":2502,"listed_count":2,"statuses_count":113999,"favourites_count":19,"account_created_at":"2013-04-04 13:52:24","verified":false,"profile_banner_url":"https://pbs.twimg.com/profile_banners/1326981402/1392098209","profile_background_url":"http://abs.twimg.com/images/themes/theme1/bg.png","profile_image_url":"http://pbs.twimg.com/profile_images/1392020385252663296/H7gKMge9_normal.jpg"},{"user_id":"1326981402","status_id":"1408756413174792197","created_at":"2021-06-26 11:57:56","screen_name":"23Sherif","text":"@GwadyM أذا كان صلاح الدين قد قال يوما:\\nكيف أضحك والمسجد الأقصى أسير . \\nفأنا أقول كيف نضحك اليوم ونهر النيل العظيم  أسير.\\nوالله وجب على شباب هذه الأمة ألا يضحكوا.. أو يلعبوا.. أو يلهوا قبل أن يتحرر المسجد الأقصى \\nونهر النيل العظيم.\\n#سد_النهضه","source":"Twitter for Android","display_text_width":140,"is_quote":false,"is_retweet":true,"favorite_count":0,"retweet_count":2,"hashtags":[null],"symbols":[null],"urls_url":[null],"urls_t.co":[null],"urls_expanded_url":[null],"media_url":[null],"media_t.co":[null],"media_expanded_url":[null],"media_type":[null],"ext_media_url":[null],"ext_media_t.co":[null],"ext_media_expanded_url":[null],"mentions_user_id":["1636266217","260664856"],"mentions_screen_name":["almesaharaty2","GwadyM"],"lang":"ar","retweet_status_id":"1408749277099302912","retweet_text":"@GwadyM أذا كان صلاح الدين قد قال يوما:\\nكيف أضحك والمسجد الأقصى أسير . \\nفأنا أقول كيف نضحك اليوم ونهر النيل العظيم  أسير.\\nوالله وجب على شباب هذه الأمة ألا يضحكوا.. أو يلعبوا.. أو يلهوا قبل أن يتحرر المسجد الأقصى \\nونهر النيل العظيم.\\n#سد_النهضه","retweet_created_at":"2021-06-26 11:29:35","retweet_source":"Twitter for Android","retweet_favorite_count":2,"retweet_retweet_count":2,"retweet_user_id":"1636266217","retweet_screen_name":"almesaharaty2","retweet_name":"المسحراتي٢","retweet_followers_count":336,"retweet_friends_count":841,"retweet_statuses_count":1362,"retweet_location":"Cairo, Egypt","retweet_description":"\u200f\u200f\u200f\u200f\u200f\u200f\u200f\u200fلن ينصلح حال هذه الأمة إلا بالعودة إلى جذورها متسلحة بأحدث ما وصل إليه العصر من علوم ومعارف.","retweet_verified":false,"geo_coords":["NA","NA"],"coords_coords":["NA","NA"],"bbox_coords":["NA","NA","NA","NA","NA","NA","NA","NA"],"status_url":"https://twitter.com/23Sherif/status/1408756413174792197","name":"sherif","location":"المملكة العربية السعودية","description":"","protected":false,"followers_count":1959,"friends_count":2502,"listed_count":2,"statuses_count":113999,"favourites_count":19,"account_created_at":"2013-04-04 13:52:24","verified":false,"profile_banner_url":"https://pbs.twimg.com/profile_banners/1326981402/1392098209","profile_background_url":"http://abs.twimg.com/images/themes/theme1/bg.png","profile_image_url":"http://pbs.twimg.com/profile_images/1392020385252663296/H7gKMge9_normal.jpg"},{"user_id":"1137975034218209280","status_id":"1408756787843584003","created_at":"2021-06-26 11:59:26","screen_name":"Hadeer27685129","text":"@na0577 @SaudiNews50 مملوك للبشر انت قلتها . اسرائيل بتمول بناء سد النهضة عشان يوقعو مصر ويدمروها بدون حرب عارف وفاهم ولا فالح تتكلم من ورا شاشة جوالك . اثيوبيا عايزة تبيع بعد كدا المياه بفلوس للدول ده بالنسبه لك ايه؟!","source":"Twitter for iPhone","display_text_width":197,"reply_to_status_id":"1408550857658994688","reply_to_user_id":"569863291","reply_to_screen_name":"na0577","is_quote":false,"is_retweet":false,"favorite_count":0,"retweet_count":0,"hashtags":[null],"symbols":[null],"urls_url":[null],"urls_t.co":[null],"urls_expanded_url":[null],"media_url":[null],"media_t.co":[null],"media_expanded_url":[null],"media_type":[null],"ext_media_url":[null],"ext_media_t.co":[null],"ext_media_expanded_url":[null],"mentions_user_id":["569863291","474886468"],"mentions_screen_name":["na0577","SaudiNews50"],"lang":"ar","geo_coords":["NA","NA"],"coords_coords":["NA","NA"],"bbox_coords":["NA","NA","NA","NA","NA","NA","NA","NA"],"status_url":"https://twitter.com/Hadeer27685129/status/1408756787843584003","name":"🇪🇬🇸🇦 ℋ𝒜𝒟ℰℰℛ","location":"Alexandria, Egypt","description":"\\"كُنْ واقعياً في كلِّ شيءٍ إلا في الدُّعاء بَالِغْ أنتَ تسألُ ربَّ المستحيل !\\" ❤","protected":false,"followers_count":63,"friends_count":139,"listed_count":0,"statuses_count":433,"favourites_count":2455,"account_created_at":"2019-06-10 06:49:25","verified":false,"profile_image_url":"http://pbs.twimg.com/profile_images/1402212438595059715/k05ljcoY_normal.jpg"},{"user_id":"4249794675","status_id":"1408756784072908800","created_at":"2021-06-26 11:59:25","screen_name":"strongsheded","text":"@ZIGO13 @nnour80 ده لو سد النهضه اشتغل حسب المخطط له  ومصر تنازلت عن النيل والميه","source":"Twitter for Android","display_text_width":64,"reply_to_status_id":"1408535400340148224","reply_to_user_id":"463168764","reply_to_screen_name":"ZIGO13","is_quote":false,"is_retweet":false,"favorite_count":0,"retweet_count":0,"hashtags":[null],"symbols":[null],"urls_url":[null],"urls_t.co":[null],"urls_expanded_url":[null],"media_url":[null],"media_t.co":[

In [6]:
len(Text),len(Text.split())

(212843, 6712)

In [7]:
type(Text)

str

In [8]:
f = open('5.1.5 Tweets.json',encoding = 'utf-8')
data = json.load(f)

In [9]:
type(data)

list

In [10]:
len(data)

100

In [11]:
data[0]

{'user_id': '2832795611',
 'status_id': '1408758089822703616',
 'created_at': '2021-06-26 12:04:36',
 'screen_name': 'amrnaga74',
 'text': '❌باقي 96ساعة\nإما نستقبل التهاني\nبعودة جيش مصر لحماية شعبه\nأو نتلقى التعازي\n#سد_النهضة\n#الجيش_المصري',
 'source': 'Twitter for Android',
 'display_text_width': 120,
 'is_quote': False,
 'is_retweet': True,
 'favorite_count': 0,
 'retweet_count': 20,
 'hashtags': ['سد_النهضة', 'الجيش_المصري'],
 'symbols': [None],
 'urls_url': [None],
 'urls_t.co': [None],
 'urls_expanded_url': [None],
 'media_url': [None],
 'media_t.co': [None],
 'media_expanded_url': [None],
 'media_type': [None],
 'ext_media_url': [None],
 'ext_media_t.co': [None],
 'ext_media_expanded_url': [None],
 'mentions_user_id': ['352489322'],
 'mentions_screen_name': ['haythamabokhal1'],
 'lang': 'ar',
 'retweet_status_id': '1408731082913193985',
 'retweet_text': '❌باقي 96ساعة\nإما نستقبل التهاني\nبعودة جيش مصر لحماية شعبه\nأو نتلقى التعازي\n#سد_النهضة\n#الجيش_المصري',
 'retweet_created_at': '2021-06-26 10:17:17',
 'retweet_source': 'Twitter for Android',
 'retweet_favorite_count': 144,
 'retweet_retweet_count': 20,
 'retweet_user_id': '352489322',
 'retweet_screen_name': 'haythamabokhal1',
 'retweet_name': 'Haytham Abokhalil هيثم أبوخليل',
 'retweet_followers_count': 571403,
 'retweet_friends_count': 781,
 'retweet_statuses_count': 42915,
 'retweet_location': 'Alexandria,Egypt',
 'retweet_description': '\u200f\u200fTV presenter& Human Rights Activist إعلامي وناشط حقوقي وسياسي مصري ـــــــــــــــ باشتغل واكتب علشان أرجع مصر من إللي خاطفينها ومستعد أدفع الفدية حياتي',
 'retweet_verified': True,
 'geo_coords': ['NA', 'NA'],
 'coords_coords': ['NA', 'NA'],
 'bbox_coords': ['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA'],
 'status_url': 'https://twitter.com/amrnaga74/status/1408758089822703616',
 'name': 'عمرو نجا',
 'location': '',
 'description': '',
 'protected': False,
 'followers_count': 152,
 'friends_count': 430,
 'listed_count': 0,
 'statuses_count': 17995,
 'favourites_count': 24044,
 'account_created_at': '2014-10-15 21:58:35',
 'verified': False,
 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/2832795611/1444404303',
 'profile_background_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
 'profile_image_url': 'http://pbs.twimg.com/profile_images/524733022692966400/qE_Vb7qp_normal.jpeg'}

In [12]:
type(data[0])

dict

In [16]:
AllKeys = []
for i in data :
    AllKeys.extend(i.keys())
len(AllKeys)
# len(set(AllKeys))

5575

In [37]:
Data = pd.DataFrame(columns = list(set(AllKeys)))

Data.head()

Empty DataFrame
Columns: [ext_media_url, symbols, media_url, retweet_count, verified, profile_background_url, retweet_text, url, source, retweet_source, place_name, retweet_retweet_count, listed_count, text, country_code, retweet_statuses_count, coords_coords, media_t.co, friends_count, place_type, followers_count, mentions_screen_name, favourites_count, reply_to_user_id, user_id, retweet_name, profile_expanded_url, urls_expanded_url, is_retweet, is_quote, retweet_user_id, place_full_name, country, media_expanded_url, bbox_coords, profile_banner_url, status_id, display_text_width, profile_image_url, ext_media_expanded_url, retweet_status_id, retweet_verified, media_type, lang, created_at, retweet_favorite_count, retweet_screen_name, retweet_friends_count, retweet_followers_count, reply_to_status_id, description, place_url, mentions_user_id, geo_coords, statuses_count, favorite_count, retweet_created_at, account_created_at, hashtags, name, reply_to_screen_name, retweet_description, profile_url, location, status_url, urls_t.co, protected, retweet_location, screen_name, ext_media_t.co, urls_url]
Index: []

[0 rows x 71 columns]

In [31]:
Data=pd.DataFrame(data=data,columns=list(set(AllKeys)))
print(Data.loc[5]["retweet_count"])
Data.head()

8

,ext_media_url,symbols,media_url,retweet_count,verified,profile_background_url,retweet_text,url,source,retweet_source,...,retweet_description,profile_url,location,status_url,urls_t.co,protected,retweet_location,screen_name,ext_media_t.co,urls_url
0,[None],[None],[None],20,False,http://abs.twimg.com/images/themes/theme1/bg.png,❌باقي 96ساعة\nإما نستقبل التهاني\nبعودة جيش مص...,NaN,Twitter for Android,Twitter for Android,...,‏‏TV presenter& Human Rights Activist إعلامي و...,NaN,,https://twitter.com/amrnaga74/status/140875808...,[None],False,"Alexandria,Egypt",amrnaga74,[None],[None]
1,[http://pbs.twimg.com/media/E4zp4czXoAU4rZZ.jpg],[None],[http://pbs.twimg.com/media/E4zp4czXoAU4rZZ.jpg],0,False,NaN,NaN,https://t.co/CQO84TklH4,TweetDeck,NaN,...,NaN,https://t.co/CQO84TklH4,cairo,https://twitter.com/ahlmasrnews0/status/140875...,[https://t.co/CqxYU3Pvoi],False,NaN,ahlmasrnews0,[https://t.co/fsOA3Mgupj],[bit.ly/3jnZJHk]
2,[None],[None],[None],3,False,NaN,وزير الخارجية المصري: تصريحات #اثيوبيا عن عمل ...,NaN,Twitter for Android,Twitter for iPhone,...,Aljazeera Media Network محرر الشؤون المصرية في...,NaN,Yemen,https://twitter.com/Alyameny6/status/140875777...,[None],False,مصر,Alyameny6,[None],[None]
3,[None],[None],[None],3,False,NaN,وزير الخارجية المصري: تصريحات #اثيوبيا عن عمل ...,NaN,Twitter for Android,Twitter for iPhone,...,Aljazeera Media Network محرر الشؤون المصرية في...,NaN,Yemen,https://twitter.com/bG0W6NTw6Y1ljNo/status/140...,[None],False,مصر,bG0W6NTw6Y1ljNo,[None],[None]
4,[None],[None],[None],5,False,http://abs.twimg.com/images/themes/theme1/bg.png,اشتري مني، التوقيت الوحيد المظبوط لحل أزمة سد ...,NaN,Twitter for iPhone,Twitter for Android,...,Where Demons Fear to Tread,NaN,Aswan,https://twitter.com/ossamamh1/status/140875713...,[None],False,Cairo,ossamamh1,[None],[None]

In [38]:
for j,i in enumerate(data) :
    Data.loc[j] = 0
    for a,b in i.items() :
        Data.loc[j,a] = str(b)

/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2832795611' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1408758089822703616' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2021-06-26 12:04:36' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'amrnaga74' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '❌باقي 96ساعة
إما نستقبل التهاني
بعودة جيش مصر لحماية شعبه
أو نتلقى التعازي
#سد_النهضة
#الجيش_المصري' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Twitter for Android' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '120' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'False' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '20' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['سد_النهضة', 'الجيش_المصري']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[None]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['352489322']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['haythamabokhal1']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'ar' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1408731082913193985' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '❌باقي 96ساعة
إما نستقبل التهاني
بعودة جيش مصر لحماية شعبه
أو نتلقى التعازي
#سد_النهضة
#الجيش_المصري' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2021-06-26 10:17:17' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Twitter for Android' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '144' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '20' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '352489322' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'haythamabokhal1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Haytham Abokhalil هيثم أبوخليل' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '571403' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '781' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '42915' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Alexandria,Egypt' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '‏‏TV presenter& Human Rights Activist إعلامي وناشط حقوقي وسياسي مصري ـــــــــــــــ باشتغل واكتب علشان أرجع مصر من إللي خاطفينها ومستعد أدفع الفدية حياتي' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['NA', 'NA']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['NA', 'NA']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '['NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA']' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'https://twitter.com/amrnaga74/status/1408758089822703616' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'عمرو نجا' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'False' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '152' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '430' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '0' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '17995' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '24044' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2014-10-15 21:58:35' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'False' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'https://pbs.twimg.com/profile_banners/2832795611/1444404303' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'http://abs.twimg.com/images/themes/theme1/bg.png' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'http://pbs.twimg.com/profile_images/524733022692966400/qE_Vb7qp_normal.jpeg' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'https://t.co/CQO84TklH4' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'https://t.co/CQO84TklH4' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'https://www.ahlmasrnews.com/' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1408550857658994688' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '569863291' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'na0577' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'https://api.twitter.com/1.1/geo/id/01db36b47425aa10.json' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)
/tmp/ipykernel_778/3166341453.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'El Daqahlia' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  Data.loc[j,a] = str(b)

In [39]:
Data.head()

,ext_media_url,symbols,media_url,retweet_count,verified,profile_background_url,retweet_text,url,source,retweet_source,...,retweet_description,profile_url,location,status_url,urls_t.co,protected,retweet_location,screen_name,ext_media_t.co,urls_url
0,[None],[None],[None],20,False,http://abs.twimg.com/images/themes/theme1/bg.png,❌باقي 96ساعة\nإما نستقبل التهاني\nبعودة جيش مص...,0,Twitter for Android,Twitter for Android,...,‏‏TV presenter& Human Rights Activist إعلامي و...,0,,https://twitter.com/amrnaga74/status/140875808...,[None],False,"Alexandria,Egypt",amrnaga74,[None],[None]
1,['http://pbs.twimg.com/media/E4zp4czXoAU4rZZ.j...,[None],['http://pbs.twimg.com/media/E4zp4czXoAU4rZZ.j...,0,False,0,0,https://t.co/CQO84TklH4,TweetDeck,0,...,0,https://t.co/CQO84TklH4,cairo,https://twitter.com/ahlmasrnews0/status/140875...,['https://t.co/CqxYU3Pvoi'],False,0,ahlmasrnews0,['https://t.co/fsOA3Mgupj'],['bit.ly/3jnZJHk']
2,[None],[None],[None],3,False,0,وزير الخارجية المصري: تصريحات #اثيوبيا عن عمل ...,0,Twitter for Android,Twitter for iPhone,...,Aljazeera Media Network محرر الشؤون المصرية في...,0,Yemen,https://twitter.com/Alyameny6/status/140875777...,[None],False,مصر,Alyameny6,[None],[None]
3,[None],[None],[None],3,False,0,وزير الخارجية المصري: تصريحات #اثيوبيا عن عمل ...,0,Twitter for Android,Twitter for iPhone,...,Aljazeera Media Network محرر الشؤون المصرية في...,0,Yemen,https://twitter.com/bG0W6NTw6Y1ljNo/status/140...,[None],False,مصر,bG0W6NTw6Y1ljNo,[None],[None]
4,[None],[None],[None],5,False,http://abs.twimg.com/images/themes/theme1/bg.png,اشتري مني، التوقيت الوحيد المظبوط لحل أزمة سد ...,0,Twitter for iPhone,Twitter for Android,...,Where Demons Fear to Tread,0,Aswan,https://twitter.com/ossamamh1/status/140875713...,[None],False,Cairo,ossamamh1,[None],[None]

In [40]:
Data.shape

(100, 71)

In [41]:
Data.to_csv('downloaded tweets.csv',encoding = 'utf-8')