In [1]:
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [3]:
npr.head(30)

                                              Article
0   In the Washington of 2016, even when the polic...
1     Donald Trump has used Twitter  —   his prefe...
2     Donald Trump is unabashedly praising Russian...
3   Updated at 2:50 p. m. ET, Russian President Vl...
4   From photography, illustration and video, to d...
5   I did not want to join yoga class. I hated tho...
6   With a   who has publicly supported the debunk...
7   I was standing by the airport exit, debating w...
8   If movies were trying to be more realistic, pe...
9   Eighteen years ago, on New Year’s Eve, David F...
10  For years now, some of the best, wildest, most...
11  For years now, some of the best, wildest, most...
12  The Colorado River is like a giant bank accoun...
13  For the last installment of NPR’s holiday reci...
14  Being overweight can raise your blood pressure...
15  Who’s the YouTube star of 2016? Adele singing ...
16  Here’s a quick roundup of some of the   you ma...
17  Ben Johnston doesn’t follow the rules of music...
18  David Bowie, Prince and George Michael are all...
19  In November, the typically straitlaced Office ...
20  This is the time of year when everybody is mak...
21  Terrorist attacks, hurricanes, a divisive U. S...
22  We all experience stress at work, no matter th...
23  When John Fahey recorded The New Possibility i...
24  This year was one of   hacks, exploding smartp...
25  From West Virginia to Wyoming, coal country ov...
26  Updated Jan. 1 at 9:56 a. m. ET, At least 39 p...
27  On the morning of Jan. 1, Los Angeles resident...
28  In September, reproductive endocrinologist Joh...
29  In an effort to take advantage of the intimate...

In [7]:
npr.shape

(11992, 1)

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm = cv.fit_transform(npr['Article'])

In [19]:
len(cv.get_feature_names_out())

54777

In [17]:
top=cv.get_feature_names_out().argmax()
print(cv.get_feature_names_out()[top])

überfunky

In [8]:
cv.vocabulary_

{'washington': 53112,
 '2016': 436,
 'policy': 37382,
 'bipartisan': 5867,
 'politics': 37411,
 'sense': 43740,
 'year': 54403,
 'shows': 44460,
 'little': 28875,
 'sign': 44648,
 'ending': 16578,
 'dec': 12950,
 '31': 604,
 'president': 38079,
 'obama': 34145,
 'moved': 32459,
 'sanction': 42732,
 'russia': 42390,
 'alleged': 2437,
 'interference': 25508,
 'election': 16123,
 'just': 26752,
 'concluded': 10646,
 'republicans': 41011,
 'long': 29070,
 'called': 7832,
 'similar': 44724,
 'severe': 43916,
 'measures': 30766,
 'scarcely': 43060,
 'bring': 7061,
 'approve': 3373,
 'house': 23698,
 'speaker': 45934,
 'paul': 36007,
 'ryan': 42428,
 'appropriate': 3364,
 'overdue': 35153,
 'prime': 38202,
 'example': 17430,
 'administration': 1762,
 'ineffective': 24926,
 'foreign': 19398,
 'left': 28266,
 'america': 2689,
 'weaker': 53234,
 'eyes': 17881,
 'world': 54102,
 'gop': 21161,
 'leaders': 28148,
 'sounded': 45783,
 'theme': 49105,
 'urging': 51889,
 'years': 54412,
 'strong': 47164,
 'action': 1610,
 'deter': 13824,
 'worldwide': 54109,
 'aggression': 2060,
 'including': 24723,
 'operations': 34619,
 'wrote': 54244,
 'rep': 40870,
 'devin': 13917,
 'nunes': 34066,
 'chairman': 8762,
 'intelligence': 25439,
 'committee': 10366,
 'weeks': 53325,
 'office': 34391,
 'suddenly': 47488,
 'decided': 12993,
 'stronger': 47165,
 'warranted': 53078,
 'appearing': 3281,
 'cnn': 9893,
 'frequent': 19762,
 'critic': 12019,
 'trent': 50204,
 'franks': 19655,
 'tougher': 49812,
 'actions': 1613,
 'said': 42561,
 'times': 49470,
 'finally': 18708,
 'tongue': 49674,
 'fox': 19572,
 'news': 33419,
 'various': 52141,
 'spokesmen': 46154,
 'trump': 50426,
 'real': 39827,
 'target': 48553,
 'russians': 42392,
 'man': 29861,
 'poised': 37339,
 'white': 53582,
 'spoke': 46150,
 'trying': 50466,
 'tie': 49395,
 'hands': 22240,
 'box': 6720,
 'meaning': 30750,
 'forced': 19362,
 'sanctions': 42735,
 'odds': 34340,
 'want': 53014,
 'moscow': 32332,
 'repeatedly': 40896,
 'closer': 9811,
 'ties': 49405,
 'cooperation': 11318,
 'fight': 18627,
 'isis': 25950,
 'battled': 5075,
 'syria': 48226,
 'behalf': 5318,
 'country': 11657,
 'embattled': 16325,
 'dictator': 14050,
 'bashar': 4980,
 'assad': 3833,
 'bombing': 6425,
 'besieged': 5584,
 'city': 9511,
 'aleppo': 2347,
 'fell': 18406,
 'forces': 19365,
 'week': 53314,
 'campaign': 7900,
 'urged': 51884,
 'missing': 31757,
 'emails': 16297,
 'private': 38259,
 'server': 43863,
 'opponent': 34646,
 'hillary': 23137,
 'clinton': 9767,
 'exchanged': 17467,
 'public': 38788,
 'russian': 42391,
 'vladimir': 52689,
 'putin': 39026,
 'occasions': 34281,
 'added': 1674,
 'doubts': 15144,
 'current': 12377,
 'levels': 28473,
 'support': 47772,
 'nato': 33055,
 'longtime': 29090,
 'nemesis': 33266,
 'suggestions': 47537,
 'extensive': 17781,
 'business': 7572,
 'dealings': 12890,
 'reason': 39886,
 'refuses': 40407,
 'release': 40655,
 'tax': 48643,
 'returns': 41375,
 'issues': 26000,
 'disquieting': 14641,
 'months': 32181,
 'sens': 43733,
 'john': 26506,
 'mccain': 30588,
 'lindsay': 28741,
 'graham': 21294,
 'prominent': 38469,
 'senior': 43729,
 'members': 30961,
 'armed': 3580,
 'services': 43874,
 'accepted': 1434,
 'assessment': 3879,
 '17': 162,
 'agencies': 2045,
 'regarding': 40428,
 'role': 41972,
 'hacking': 21995,
 'democratic': 13431,
 'committees': 10368,
 'includes': 24722,
 'fbi': 18299,
 'cia': 9408,
 'consensus': 10925,
 'goal': 21015,
 'discredit': 14412,
 'american': 2690,
 'democracy': 13429,
 'defeat': 13142,
 'elect': 16118,
 'say': 42985,
 'great': 21450,
 'majority': 29743,
 'senate': 43714,
 'colleagues': 10127,
 'agree': 2093,
 'slated': 45045,
 'hearing': 22694,
 'cyberthreats': 12483,
 'jan': 26168,
 'politicizing': 37407,
 'idea': 24153,
 'helped': 22874,
 'win': 53777,
 'issue': 25998,
 'difficult': 14104,
 'republican': 41009,
 'allowed': 2491,
 'supporters': 47775,
 'push': 39005,
 'entire': 16798,
 'designed': 13733,
 'undermine': 51084,
 'legitimacy': 28309,
 'leader': 28146,
 'mitch': 31816,
 'mcconnell': 30609,
 'far': 18123,
 'resisted': 41140,
 'calls': 7845,
 'select': 43654,
 'look': 29096,
 'sen': 43712,
 'richard': 41585,
 'burr': 7531,
 'typically': 50727,
 'evidence': 17360,
 'actual': 1632,
 'voting': 52788,
 'tallying': 48416,
 'nov': 33967,
 'compromised': 10568,
 'true': 50413,
 'red': 40177,
 'herring': 23003,
 'functions': 19976,
 'focus': 19226,
 'concern': 10625,
 'shown': 44454,
 'delving': 13388,
 'happened': 22306,
 'cast': 8369,
 'doubt': 15137,
 'reports': 40955,
 'date': 12781,
 'suggested': 47533,
 'really': 39848,
 'knows': 27447,
 'computers': 10583,
 'make': 29746,
 'know': 27439,
 'using': 51934,
 'time': 49459,
 'lives': 28894,
 'important': 24521,
 'things': 49182,
 'end': 16560,
 'did': 14059,
 'briefing': 7023,
 'subject': 47320,
 'wanted': 53015,
 'daily': 12573,
 'briefings': 7024,
 'available': 4289,
 'recent': 40001,
 'preferring': 37960,
 'given': 20817,
 'men': 30994,
 'chosen': 9300,
 'vice': 52419,
 'mike': 31387,
 'pence': 36227,
 'national': 33036,
 'security': 43555,
 'adviser': 1884,
 'flynn': 19208,
 'taking': 48373,
 'occasionally': 34279,
 'irony': 25878,
 'controversy': 11214,
 'arising': 3546,
 'eleventh': 16186,
 'hour': 23693,
 'presidency': 38078,
 'overstated': 35273,
 'defines': 13200,
 'dilemma': 14145,
 'facing': 17937,
 'outgoing': 34982,
 'incoming': 24734,
 'party': 35843,
 'control': 11204,
 'appears': 3282,
 'reluctant': 40711,
 'retaliate': 41292,
 'fear': 18311,
 'interfere': 25506,
 'greater': 21452,
 'confrontation': 10799,
 'usually': 51944,
 'resisting': 41142,
 'join': 26516,
 'punishing': 38907,
 'economic': 15873,
 'annexation': 3013,
 'crimea': 11972,
 'painful': 35453,
 'coming': 10297,
 'alongside': 2525,
 'falling': 18042,
 'prices': 38168,
 'oil': 34435,
 'commodity': 10373,
 'keeps': 27013,
 'economy': 15880,
 'afloat': 1993,
 'despite': 13766,
 'provocations': 38684,
 'surrogates': 47862,
 'overt': 35290,
 'moves': 32465,
 'force': 19361,
 'hand': 22194,
 'believed': 5376,
 'critical': 12020,
 'computer': 10581,
 'systems': 48239,
 'neighboring': 33245,
 'ukraine': 50789,
 'estonia': 17176,
 'poland': 37361,
 'following': 19283,
 'chorus': 9297,
 'confirmation': 10771,
 'community': 10406,
 'political': 37400,
 'acted': 1608,
 'imposed': 24530,
 'set': 43886,
 'diplomatic': 14230,
 'sanctioning': 42734,
 'officials': 34400,
 'closing': 9819,
 'compounds': 10551,
 'expelling': 17651,
 '35': 650,
 'diplomats': 14232,
 'damaging': 12612,
 'taken': 48364,
 'covertly': 11721,
 'held': 22836,
 'hope': 23558,
 'visible': 52630,
 'portion': 37606,
 'program': 38412,
 'amounted': 2752,
 'major': 29738,
 'retribution': 41351,
 'saw': 42968,
 'fit': 18861,
 'diminish': 14170,
 'declining': 13033,
 'respond': 41193,
 'government': 21228,
 'steadfastly': 46645,
 'denied': 13495,
 'rejected': 40600,
 'minister': 31564,
 'recommended': 40076,
 'package': 35394,
 'responses': 41202,
 'sent': 43762,
 'invitation': 25790,
 'send': 43718,
 'children': 9156,
 'holiday': 23350,
 'appear': 3277,
 'moment': 32049,
 'bigger': 5724,
 'spurned': 46286,
 'kept': 27081,
 'looked': 29097,
 'like': 28659,
 'bromance': 7147,
 'tweeted': 50662,
 'delay': 13296,
 'knew': 27404,
 'smart': 45257,
 'overall': 35104,
 'question': 39189,
 'amounts': 2754,
 'crisis': 12000,
 'grasp': 21385,
 'relationship': 40633,
 'mitt': 31837,
 'romney': 42012,
 'greatest': 21453,
 'threat': 49262,
 'sure': 47800,
 'needs': 33194,
 'dispel': 14585,
 'ability': 1288,
 'stand': 46493,
 'bullied': 7397,
 'cajoled': 7760,
 'way': 53211,
 'center': 8647,
 'stage': 46419,
 'affairs': 1932,
 'determined': 13837,
 'turn': 50587,
 'page': 35436,
 'past': 35891,
 'commitments': 10363,
 'free': 19711,
 'trade': 49906,
 'philosophy': 36685,
 'funding': 19989,
 'united': 51402,
 'nations': 33048,
 'twitter': 50697,
 'account': 1489,
 'guide': 21789,
 'conundrum': 11215,
 'perceive': 36306,
 'play': 37132,
 'rules': 42314,
 'ago': 2084,
 'confident': 10755,
 'work': 54067,
 'presidential': 38081,
 'works': 54092,
 'oval': 35089,
 'donald': 15010,
 'used': 51918,
 'preferred': 37959,
 'means': 30755,
 'communication': 10394,
 'weigh': 53337,
 'swath': 47998,
 'comments': 10342,
 'glimpse': 20910,
 'deal': 12884,
 'pressing': 38093,
 'matters': 30462,
 'highlight': 23101,
 'reactionary': 39792,
 'social': 45523,
 'media': 30806,
 'immediately': 24366,
 'spur': 46282,
 'international': 25555,
 'attention': 4077,
 'staff': 46410,
 'indicated': 24836,
 'air': 2178,
 'concerns': 10628,
 'grievances': 21548,
 'won': 53991,
 'enters': 16776,
 'wednesday': 53304,
 'blasted': 6041,
 'abstention': 1365,
 'council': 11594,
 'vote': 52782,
 'israeli': 25991,
 'settlements': 43902,
 'earlier': 15741,
 'month': 32178,
 'tweets': 50666,
 'came': 7879,
 'hours': 23697,
 'secretary': 43530,
 'state': 46581,
 'kerry': 27102,
 'gave': 20378,
 'speech': 45999,
 'defending': 13168,
 'decision': 13005,
 'calling': 7838,
 'continued': 11144,
 'building': 7364,
 'palestinian': 35515,
 'territory': 48976,
 'west': 53440,
 'bank': 4773,
 'solution': 45645,
 'region': 40451,
 'israel': 25990,
 'benjamin': 5478,
 'netanyahu': 33316,
 'fraught': 19679,
 'biggest': 5725,
 'forthcoming': 19512,
 'shift': 44239,
 'immediate': 24365,
 'administrations': 1763,
 'pledged': 37184,
 'steadfast': 46644,
 'ally': 2507,
 'underscore': 51119,
 'replied': 40943,
 'morning': 32288,
 'thanking': 49071,
 'jr': 26620,
 'ivanka': 26040,
 'close': 9807,
 'advisers': 1885,
 'converted': 11249,
 'judaism': 26632,
 'married': 30217,
 'husband': 23959,
 'jared': 26209,
 'kushner': 27647,
 'official': 34397,
 'told': 49613,
 'detailed': 13800,
 'sensitive': 43750,
 'information': 25055,
 'proving': 38674,
 'worked': 54076,
 'resolution': 41149,
 'claims': 9541,
 'veto': 52376,
 'different': 14094,
 'come': 10262,
 'inauguration': 24650,
 'monday': 32074,
 'settlement': 43901,
 'forefront': 19390,
 'days': 12834,
 'weighed': 53338,
 'nuclear': 34024,
 'tweet': 50661,
 'strengthen': 47083,
 'arsenal': 3663,
 'msnbc': 32508,
 'joe': 26488,
 'reported': 40950,
 'arms': 3600,
 'race': 39320,
 'outmatch': 35015,
 'pass': 35860,
 'post': 37667,
 'dan': 12635,
 'zak': 54593,
 'npr': 33992,
 'robert': 41861,
 'siegel': 44614,
 'considered': 10957,
 'friday': 19795,
 'inconsistent': 24753,
 'statements': 46591,
 'weapons': 53251,
 'use': 51917,
 'horror': 23617,
 'understand': 51132,
 'capable': 8029,
 'doing': 14949,
 'matter': 30459,
 'countries': 11655,
 'south': 45814,
 'korea': 27506,
 'japan': 26203,
 'tacitly': 48281,
 'endorse': 16590,
 'proliferation': 38457,
 'going': 21073,
 'decades': 12955,
 'slammed': 45022,
 'china': 9189,
 'seizure': 43647,
 'unmanned': 51468,
 'navy': 33106,
 'underwater': 51161,
 'drone': 15400,
 'unpresidented': 51542,
 'correcting': 11468,
 'typo': 50733,
 'new': 33390,
 'talks': 48402,
 'pentagon': 36277,
 'agreed': 2097,
 'return': 41370,
 'later': 27998,
 'stoked': 46907,
 'tensions': 48906,
 'stark': 46541,
 'break': 6899,
 'protocol': 38637,
 'phone': 36696,
 'taiwanese': 48350,
 'tsai': 50472,
 'beijing': 5345,
 'considers': 10959,
 'taiwan': 48349,
 'renegade': 40816,
 'province': 38671,
 'doesn': 14927,
 'recognize': 40062,
 'don': 15008,
 'operated': 34612,
 'away': 4369,
 'jobs': 26473,
 'claimed': 9539,
 'intentionally': 25462,
 'devaluing': 13884,
 'currency': 12376,
 'boost': 6519,
 'exports': 17737,
 'companies': 10421,
 'manufacture': 30011,
 'goods': 21138,
 'york': 54502,
 'story': 46966,
 'noted': 33924,
 'daughter': 12792,
 'clothing': 9830,
 'shoe': 44327,
 'lines': 28754,
 'apparel': 3267,
 'line': 28744,
 'overseas': 35248,
 'unabashedly': 50842,
 'praising': 37817,
 'day': 12823,
 'issued': 25999,
 'tough': 49809,
 'response': 41201,
 'cyberattacks': 12474,
 'intended': 25445,
 'influence': 25033,
 'elections': 16125,
 'afternoon': 2021,
 'responded': 41194,
 'expel': 17649,
 'kind': 27254,
 'ordered': 34755,
 'leave': 28207,
 'admiring': 1777,
 'strategic': 47036,
 'approach': 3359,
 'ongoing': 34555,
 'praise': 37813,
 'instead': 25341,
 'signaled': 44651,
 'wait': 52895,
 'decide': 12992,
 'forward': 19533,
 'takes': 48370,
 'giving': 20826,
 'friendlier': 19807,
 'quite': 39265,
 'generous': 20497,
 'embassy': 16324,
 'retweeted': 41377,
 'pinned': 36920,
 'timeline': 49464,
 'remain': 40717,
 'posted': 37674,
 'instagram': 25325,
 'thursday': 49346,
 'stinging': 46851,
 'rebuke': 39956,
 'directed': 14240,
 'hacks': 22000,
 'personal': 36470,
 'email': 16294,
 'nominee': 33706,
 'podesta': 37305,
 'statement': 46590,
 'americans': 2695,
 'alarmed': 2286,
 'stands': 46509,
 'contrast': 11186,
 'congressional': 10845,
 'backed': 4494,
 'albeit': 2308,
 'criticizing': 12027,
 'late': 27994,
 'stance': 46490,
 'does': 14926,
 'share': 44086,
 'interests': 25500,
 'friends': 19811,
 'good': 21121,
 'initial': 25154,
 'step': 46732,
 'pointed': 37330,
 'impact': 24407,
 'europe': 17272,
 'wake': 52916,
 'maintaining': 29722,
 'damaged': 12610,
 'isolated': 25977,
 'released': 40656,
 'brief': 7017,
 'evening': 17329,
 'latest': 28000,
 'simply': 44750,
 'stating': 46602,
 'better': 5625,
 'meet': 30862,
 'cyberhacking': 12479,
 'findings': 18722,
 'dismissed': 14544,
 'attacks': 4055,
 'raised': 39474,
 'eyebrows': 17869,
 'running': 42355,
 'unlike': 51444,
 'interview': 25628,
 'december': 12978,
 '2015': 435,
 'pressed': 38090,
 'host': 23654,
 'scarborough': 43058,
 'killings': 27226,
 'figures': 18642,
 'journalists': 26596,
 'deflected': 13214,
 'praised': 37814,
 'talented': 48382,
 'aides': 2151,
 'joke': 26524,
 'tried': 50261,
 'distancing': 14712,
 'met': 31142,
 'nice': 33487,
 'thing': 49181,
 'genius': 20515,
 'thank': 49067,
 'newspaper': 33441,
 'heavily': 22751,
 'criticized': 12025,
 'saying': 42989,
 'wasn': 53116,
 'annexed': 3014,
 'repeated': 40895,
 'town': 49849,
 'hall': 22099,
 'early': 15744,
 'september': 43792,
 'memorable': 30975,
 'clashes': 9597,
 'debates': 12921,
 'accused': 1521,
 'puppet': 38932,
 'shot': 44409,
 'criticizes': 12026,
 'reset': 41097,
 'led': 28236,
 'relations': 40632,
 'increasingly': 24773,
 'feed': 18367,
 'violating': 52568,
 'usual': 51943,
 'protocols': 38638,
 'winner': 53832,
 'avoids': 4343,
 'interfering': 25510,
 'sitting': 44873,
 'outlined': 35005,
 'opposition': 34660,
 'states': 46593,
 'recently': 40002,
 'encourage': 16545,
 'believes': 5379,
 'updated': 51784,
 '50': 808,
 'et': 17190,
 'says': 42993,
 'depending': 13576,
 'took': 49687,
 'announced': 3028,
 'meant': 30756,
 'sergey': 43838,
 'lavrov': 28075,
 'went': 53421,
 'tv': 50644,
 'antics': 3126,
 'unanswered': 50876,
 'provided': 38665,
 'cyber': 12471,
 'lucian': 29286,
 'kim': 27240,
 'kremlin': 27557,
 'consistently': 10967,
 'accusations': 1518,
 'hackers': 21994,
 'broken': 7138,
 'sway': 48003,
 'notes': 33925,
 'proposed': 38551,
 'specific': 45958,
 'executive': 17520,
 'order': 34754,
 'described': 13694,
 'operatives': 34621,
 'expelled': 17650,
 'facilities': 17935,
 'closed': 9808,
 'individuals': 24879,
 'organizations': 34789,
 'publicized': 38797,
 'plans': 37081,
 'plan': 37065,
 'needed': 33183,
 'approval': 3371,
 'lose': 29164,
 'access': 1437,
 'buildings': 7365,
 'longer': 29072,
 'able': 1293,
 'retreats': 41348,
 'maryland': 30293,
 'sort': 45756,
 'happening': 22307,
 'provocative': 38685,
 'grounds': 21669,
 'reserve': 41090,
 'right': 41663,
 'stoop': 46935,
 'level': 28470,
 'irresponsible': 25903,
 'diplomacy': 14227,
 'translated': 50049,
 'barred': 4917,
 'regrettable': 40474,
 'term': 48933,
 'manner': 29973,
 'offer': 34385,
 'greetings': 21510,
 'family': 18079,
 'season': 43486,
 'people': 36283,
 'wish': 53885,
 'happiness': 22314,
 'prosperity': 38591,
 'photography': 36720,
 'illustration': 24297,
 'video': 52452,
 'data': 12773,
 'visualizations': 52648,
 'immersive': 24375,
 'experiences': 17663,
 'visuals': 52653,
 'storytelling': 46975,
 'interwoven': 25639,
 'written': 54232,
 'spoken': 46151,
 'word': 54055,
 'images': 24312,
 'visual': 52646,
 'language': 27889,
 'create': 11885,
 'deeper': 13117,
 'understanding': 51135,
 'empathy': 16446,
 'struggles': 47184,
 'triumphs': 50330,
 'face': 17913,
 'lot': 29172,
 'stories': 46956,
 'list': 28824,
 'small': 45249,
 'selection': 43657,
 'favorite': 18274,
 'pieces': 36817,
 'highlighting': 23104,
 'proud': 38649,
 'fun': 19967,
 'telling': 48825,
 'transport': 50083,
 'rocky': 41925,
 'mountain': 32418,
 'park': 35751,
 'sights': 44640,
 'sounds': 45788,
 'geology': 20567,
 'lesson': 28438,
 'oregon': 34767,
 'university': 51417,
 'professor': 38375,
 'eric': 17008,
 'kirby': 27305,
 'discusses': 14433,
 'geologic': 20562,
 'history': 23236,
 'rockies': 41914,
 'today': 49579,
 'indians': 24834,
 'energy': 16624,
 'person': 36466,
 'chinese': 9193,
 'population': 37555,
 'live': 28883,
 'roughly': 42152,
 'electricity': 16137,
 'night': 33545,
 'refrigerator': 40385,
 'car': 8100,
 'ambitious': 2657,
 'goals': 21020,
 'improve': 24583,
 'standard': 46495,
 'living': 28903,
 '400': 707,
 'million': 31464,
 'lacking': 27727,
 'reliable': 40671,
 'need': 33182,
 'enhance': 16671,
 'supply': 47770,
 'ajay': 2244,
 'mathur': 30436,
 'climate': 9736,
 'expert': 17678,
 'runs': 42358,
 'resources': 41173,
 'institute': 25357,
 'delhi': 13320,
 'fast': 18197,
 'india': 24829,
 'increases': 24771,
 'clean': 9645,
 'solar': 45598,
 'wind': 53785,
 'probably': 38286,
 'double': 15129,
 'coal': 9902,
 '2030': 452,
 'todd': 49580,
 'stern': 46772,
 'served': 43862,
 'till': 49439,
 'envoy': 16871,
 'change': 8815,
 'steeper': 46686,
 'hill': 23135,
 'climb': 9742,
 'challenge': 8776,
 'looking': 29099,
 'number': 34053,
 'growth': 21698,
 'sacred': 42486,
 'dead': 12864,
 'yamuna': 54352,
 'river': 41787,
 'saved': 42945,
 'big': 5721,
 'battle': 5074,
 'development': 13895,
 'vs': 52812,
 'pollution': 37441,
 'sundarbans': 47630,
 'tigers': 49413,
 'try': 50464,
 'coexist': 10010,
 'shrinking': 44486,
 'space': 45852,
 'organization': 34786,
 'daunting': 12795,
 'task': 48586,
 'best': 5591,
 'clues': 9865,
 'privately': 38260,
 'financial': 18713,
 'disclosure': 14365,
 'form': 19465,
 'document': 14904,
 'covers': 11719,
 'scores': 43277,
 'pages': 35442,
 'type': 50713,
 'suggests': 47539,
 'financially': 18715,
 'involved': 25807,
 'hundreds': 23894,
 'license': 28573,
 'dive': 14793,
 'submitted': 47348,
 'ethics': 17215,
 'largest': 27942,
 'sources': 45803,
 'revenue': 41415,
 'golf': 21095,
 'courses': 11686,
 'rents': 40855,
 'flung': 19184,
 'include': 24720,
 'retail': 41279,
 'entertainment': 16783,
 'affected': 1936,
 'policies': 37380,
 'scoured': 43301,
 'overview': 35314,
 ...}

In [6]:
dtm.shape

(11992, 54777)

In [10]:
import random
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(cv.get_feature_names_out()[random_word_id])

courtesan
bivens
choate
orfield
steen
honoring
postdoc
dehaan
facilitated
mortifying

In [67]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.decomposition import LatentDirichletAllocation
documents = [
    "football team goal match coach",
    "basketball player score game",
    "government election president vote",
    "minister parliament politics law",
    "python machine learning neural network",
    "deep learning tensorflow pytorch",
    "football stadium striker coach",
    "AI transformer language model"
]
vectorizer = CountVectorizer(stop_words="english")

X = vectorizer.fit_transform(documents)
lda = LatentDirichletAllocation(
    n_components=3,
    random_state=42
)
results=lda.fit_transform(X)
print(lda.components_.shape)
# print(lda.components_)
feature_names = vectorizer.get_feature_names_out()

for topic_idx, topic in enumerate(lda.components_):
    print(f"Topic {topic_idx}")

    top_words = topic.argsort()[::-1][:5]

    print(feature_names[top_words])
for i,prob in enumerate(results):
    print(i,">>>>",prob)
most=results.argmax(axis=1)
df=pd.DataFrame(most,columns=['topic'])
print(df)

(3, 31)
Topic 0
['transformer' 'language' 'model' 'ai' 'learning']
Topic 1
['learning' 'president' 'vote' 'government' 'election']
Topic 2
['coach' 'football' 'team' 'goal' 'match']
0 >>>> [0.05618217 0.05594385 0.88787398]
1 >>>> [0.0676328  0.06726589 0.86510131]
2 >>>> [0.06741917 0.86555012 0.06703071]
3 >>>> [0.06741917 0.86555012 0.06703071]
4 >>>> [0.05635363 0.05826245 0.88538392]
5 >>>> [0.06741565 0.86362167 0.06896268]
6 >>>> [0.06737111 0.06710439 0.8655245 ]
7 >>>> [0.86614522 0.06695931 0.06689547]
   topic
0      2
1      2
2      1
3      1
4      2
5      1
6      2
7      0

In [47]:
from sklearn.decomposition import LatentDirichletAllocation
LDA = LatentDirichletAllocation(n_components=7,random_state=42)
LDA.fit_transform(dtm)

array([[1.61040465e-02, 6.83341493e-01, 2.25376318e-04, ...,
        2.99652737e-01, 2.25479379e-04, 2.25497980e-04],
       [3.63424997e-02, 8.86130697e-01, 4.40751747e-04, ...,
        7.57636804e-02, 4.40866779e-04, 4.40835574e-04],
       [3.28569485e-04, 6.96344889e-01, 3.28302105e-04, ...,
        3.02012902e-01, 3.28724083e-04, 3.28352652e-04],
       ...,
       [1.44467964e-02, 1.60696622e-01, 1.73678310e-01, ...,
        2.24636569e-02, 3.98728349e-04, 3.98359730e-04],
       [4.33560738e-04, 3.53196803e-02, 4.33022554e-04, ...,
        9.62512640e-01, 4.33971991e-04, 4.33490254e-04],
       [3.98777533e-01, 2.54376049e-04, 3.59290659e-01, ...,
        2.40914375e-01, 2.54445555e-04, 2.54253739e-04]])

In [48]:
LDA.components_.shape

(7, 54777)

In [49]:
len(LDA.components_)

7

In [24]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [25]:
len(LDA.components_) , len(LDA.components_[0])

(7, 54777)

In [26]:
single_topic = LDA.components_[0]
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [ ]:
single_topic.argsort()[-10:]

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993], dtype=int64)

In [ ]:
for index in single_topic.argsort()[-10:]:
    print(cv.get_feature_names_out()[index])

new
percent
government
company
million
care
people
health
said
says

In [32]:
import spacy

nlp = spacy.load("en_core_web_sm")

for index, topic in enumerate(LDA.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC #{index+1}")

    words = [cv.get_feature_names_out()[i] for i in topic.argsort()[-15:]]

    doc = nlp(" ".join(words))

    print(", ".join(
        token.lemma_.lower()
        for token in doc
        if token.is_alpha
    ))

    print()

THE TOP 15 WORDS FOR TOPIC #1
company, money, year, federal, new, percent, government, company, million, care, people, health, say, say

THE TOP 15 WORDS FOR TOPIC #2
military, house, security, russia, government, npr, report, say, news, people, tell, police, president, trump, say

THE TOP 15 WORDS FOR TOPIC #3
way, world, family, home, day, time, water, city, new, year, food, just, people, like, say

THE TOP 15 WORDS FOR TOPIC #4
time, new, don, year, medical, disease, patient, just, child, study, like, woman, health, people, say

THE TOP 15 WORDS FOR TOPIC #5
voter, vote, election, party, new, obama, court, republican, campaign, people, state, president, clinton, say, trump

THE TOP 15 WORDS FOR TOPIC #6
year, go, ve, life, don, new, way, music, really, time, know, think, people, just, like

THE TOP 15 WORDS FOR TOPIC #7
student, year, datum, science, university, people, time, school, just, education, new, like, student, school, say

In [53]:
topic_results = LDA.transform(dtm)

In [34]:
topic_results.shape

(11992, 7)

In [35]:
LDA.components_.shape

(7, 54777)

array([42993, 42561, 42993, 42993, 50426, 28659, 42993])

In [36]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [43]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0])

In [44]:
set(topic_results.argmax(axis=1))

{np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6)}

In [38]:
npr['Topic'] = topic_results.argmax(axis=1)
npr.head(10)

                                             Article  Topic
0  In the Washington of 2016, even when the polic...      1
1    Donald Trump has used Twitter  —   his prefe...      1
2    Donald Trump is unabashedly praising Russian...      1
3  Updated at 2:50 p. m. ET, Russian President Vl...      1
4  From photography, illustration and video, to d...      2
5  I did not want to join yoga class. I hated tho...      3
6  With a   who has publicly supported the debunk...      3
7  I was standing by the airport exit, debating w...      2
8  If movies were trying to be more realistic, pe...      3
9  Eighteen years ago, on New Year’s Eve, David F...      2