In [1]:
import pandas as pd
npr = pd.read_csv('npr.csv')
npr.head()

                                             Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import NMF

documents = [
    "I love football and basketball",
    "The team scored many goals",
    "Python is used in machine learning",
    "Deep learning uses neural networks"
]

vectorizer = TfidfVectorizer(stop_words="english")
X = vectorizer.fit_transform(documents)

nmf = NMF(n_components=2, random_state=42)

W = nmf.fit_transform(X)
H = nmf.components_

words = vectorizer.get_feature_names_out()

for i, topic in enumerate(H):
    print(f"Topic {i+1}:")
    print([words[j] for j in topic.argsort()[-5:][::-1]])
for idx, doc in enumerate(W):
    print("propability is :",doc)
    print(f"Document {idx+1} belongs to topic {doc.argmax()+1}")

Topic 1:
['learning', 'used', 'machine', 'python', 'uses']
Topic 2:
['football', 'love', 'basketball', 'goals', 'scored']
propability is : [0.         0.83083182]
Document 1 belongs to topic 2
propability is : [0.00056374 0.11344775]
Document 2 belongs to topic 2
propability is : [0.59388428 0.        ]
Document 3 belongs to topic 1
propability is : [0.59388422 0.        ]
Document 4 belongs to topic 1

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_df=0.95, min_df=2, stop_words='english')
dtm = tfidf.fit_transform(npr['Article'])

In [8]:
from sklearn.decomposition import NMF
nmf_model = NMF(n_components=7,random_state=42)
nmf_model.fit_transform(dtm)

NMF(n_components=7, random_state=42)

In [10]:
len(tfidf.get_feature_names_out())

54777

In [32]:
print(dtm)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 3033388 stored elements and shape (11992, 54777)>
  Coords	Values
  (0, 162)	0.02420777972617735
  (0, 436)	0.057426739142936785
  (0, 604)	0.02813089107375168
  (0, 650)	0.02653652777634085
  (0, 1288)	0.022444232597226586
  (0, 1434)	0.028763633914840978
  (0, 1489)	0.023797160985101363
  (0, 1608)	0.03226897967994956
  (0, 1610)	0.020693641331932487
  (0, 1613)	0.07253465437685629
  (0, 1632)	0.025308912294465632
  (0, 1674)	0.019103596848232273
  (0, 1762)	0.01769876741664019
  (0, 1884)	0.025404296400493524
  (0, 1932)	0.027002284256125587
  (0, 1993)	0.044568871723068615
  (0, 2045)	0.07533311505887269
  (0, 2060)	0.03834335311134389
  (0, 2084)	0.01503938612876087
  (0, 2093)	0.048837638128549916
  (0, 2347)	0.034912922268184154
  (0, 2437)	0.05672110592908611
  (0, 2491)	0.042025802920180926
  (0, 2525)	0.028380087248686587
  (0, 2689)	0.01670021921556781
  :	:
  (11991, 52783)	0.1523252769688231
  (11991, 52786)	0.032524386440987006
  (11991, 52788)	0.03858014866091517
  (11991, 52977)	0.051456321449467435
  (11991, 53014)	0.009862718553798774
  (11991, 53015)	0.013306666081953262
  (11991, 53064)	0.021036892826114022
  (11991, 53142)	0.01997958477400182
  (11991, 53259)	0.01999021823005047
  (11991, 53325)	0.014329342052327557
  (11991, 53567)	0.038494724758669545
  (11991, 53582)	0.04623269406439067
  (11991, 53746)	0.0186341094732588
  (11991, 53797)	0.024233439727215644
  (11991, 53989)	0.012666666801867094
  (11991, 53992)	0.020355565669501998
  (11991, 54076)	0.01428876121632034
  (11991, 54078)	0.01667509354838575
  (11991, 54082)	0.023937590422362005
  (11991, 54092)	0.03048247160022551
  (11991, 54113)	0.028069289442195427
  (11991, 54120)	0.018563167128126532
  (11991, 54145)	0.023974664696450227
  (11991, 54403)	0.00853020207284055
  (11991, 54412)	0.007454565657515725

In [12]:
print("shape of tfidf ",dtm.shape)
print("shape of document ",nmf_model.fit_transform(dtm).shape)
print("shape of nmf model ",nmf_model.components_.shape)

shape of tfidf  (11992, 54777)
shape of document  (11992, 7)
shape of nmf model  (7, 54777)

In [14]:
import random
for i in range(10):
    random_word_id = random.randint(0,54776)
    print(tfidf.get_feature_names_out()[random_word_id])

heiko
lampposts
toms
kjzz
fumbled
unsee
bopping
sky
indoctrination
cycle

In [15]:
len(nmf_model.components_)

7

In [16]:
nmf_model.components_

len(nmf_model.components_[0])

54777

In [17]:
single_topic = nmf_model.components_[0]

single_topic.argsort()

array([29744, 41477, 41476, ..., 36283, 54692, 42993])

In [18]:
len(single_topic)

54777

In [ ]:
single_topic[18302]

0.0

In [19]:
single_topic[42993]

np.float64(2.0162023252917587)

In [20]:
single_topic.argsort()[-10:]

array([14441, 36310, 53989, 52615, 47218, 53152, 19307, 36283, 54692,
       42993])

In [22]:
top_word_indices = single_topic.argsort()[-10:]

for index in top_word_indices:
    print(tfidf.get_feature_names_out()[index])

disease
percent
women
virus
study
water
food
people
zika
says

In [24]:
for index,topic in enumerate(nmf_model.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([tfidf.get_feature_names_out()[i] for i in topic.argsort()[-15:]])
    print('\n')

dtm.shape

THE TOP 15 WORDS FOR TOPIC #0
['new', 'research', 'like', 'patients', 'health', 'disease', 'percent', 'women', 'virus', 'study', 'water', 'food', 'people', 'zika', 'says']


THE TOP 15 WORDS FOR TOPIC #1
['gop', 'pence', 'presidential', 'russia', 'administration', 'election', 'republican', 'obama', 'white', 'house', 'donald', 'campaign', 'said', 'president', 'trump']


THE TOP 15 WORDS FOR TOPIC #2
['senate', 'house', 'people', 'act', 'law', 'tax', 'plan', 'republicans', 'affordable', 'obamacare', 'coverage', 'medicaid', 'insurance', 'care', 'health']


THE TOP 15 WORDS FOR TOPIC #3
['officers', 'syria', 'security', 'department', 'law', 'isis', 'russia', 'government', 'state', 'attack', 'president', 'reports', 'court', 'said', 'police']


THE TOP 15 WORDS FOR TOPIC #4
['primary', 'cruz', 'election', 'democrats', 'percent', 'party', 'delegates', 'vote', 'state', 'democratic', 'hillary', 'campaign', 'voters', 'sanders', 'clinton']


THE TOP 15 WORDS FOR TOPIC #5
['love', 've', 'don', 'album', 'way', 'time', 'song', 'life', 'really', 'know', 'people', 'think', 'just', 'music', 'like']


THE TOP 15 WORDS FOR TOPIC #6
['teacher', 'state', 'high', 'says', 'parents', 'devos', 'children', 'college', 'kids', 'teachers', 'student', 'education', 'schools', 'school', 'students']

(11992, 54777)

In [25]:
len(npr)

11992

In [26]:
topic_results = nmf_model.transform(dtm)

topic_results.shape

(11992, 7)

In [27]:
topic_results[0].round(2)

array([0.  , 0.12, 0.  , 0.06, 0.02, 0.  , 0.  ])

In [28]:
topic_results[0].argmax()

np.int64(1)

In [29]:
npr.head()

                                             Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [30]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 0, 4, 3])

In [31]:
npr['Topic'] = topic_results.argmax(axis=1)



topicdict  = {0:'health',1:'election',2:'legis',3:'policy',4:'candidates',5:'music',6:'educaion'}

npr['Topic Label'] = npr['Topic'].map(topicdict)

npr.head(10)

                                             Article  Topic Topic Label
0  In the Washington of 2016, even when the polic...      1    election
1    Donald Trump has used Twitter  —   his prefe...      1    election
2    Donald Trump is unabashedly praising Russian...      1    election
3  Updated at 2:50 p. m. ET, Russian President Vl...      3      policy
4  From photography, illustration and video, to d...      6    educaion
5  I did not want to join yoga class. I hated tho...      5       music
6  With a   who has publicly supported the debunk...      0      health
7  I was standing by the airport exit, debating w...      0      health
8  If movies were trying to be more realistic, pe...      0      health
9  Eighteen years ago, on New Year’s Eve, David F...      5       music