#Shell Command

In [ ]:
!pwd

/content

In [ ]:
!ls

hello.py  run.sh  sample_data  test.txt

In [ ]:
%time sum(range(1000000))

CPU times: user 23 ms, sys: 0 ns, total: 23 ms
Wall time: 23 ms

499999500000

1: **Write text to a file**

In [ ]:
%%writefile hello.py
print("Hello")
print("World")

Overwriting hello.py

In [ ]:
!python hello.py

Hello
World

In [ ]:
%%writefile run.sh
echo "Training started"
python train.py
echo "Training finished"

Writing run.sh

In [ ]:
!sh run.sh
!bash run.sh

Training started
python3: can't open file '/content/train.py': [Errno 2] No such file or directory
Training finished
Training started
python3: can't open file '/content/train.py': [Errno 2] No such file or directory
Training finished

In [ ]:
%%writefile test.txt
Hello Mohamed!
Welcome to NLP.
This is line 3.

Writing test.txt

In [ ]:
my_file = open('test.txt',mode='r',encoding='utf-8')
for line in my_file:
    print(line)

Hello Mohamed!

Welcome to NLP.

This is line 3.

In [ ]:
my_file.read()

''

In [ ]:
my_file.seek(0)

0

In [ ]:
my_file.readlines()

['Hello Mohamed!\n', 'Welcome to NLP.\n', 'This is line 3.\n']

In [ ]:
my_file.close()

| Mode   | Meaning                 | File must exist? | Creates file? | Erases existing content? |
| ------ | ----------------------- | ---------------- | ------------- | ------------------------ |
| `"r"`  | Read                    | ✅ Yes            | ❌ No          | ❌ No                     |
| `"w"`  | Write                   | ❌ No             | ✅ Yes         | ✅ Yes                    |
| `"a"`  | Append                  | ❌ No             | ✅ Yes         | ❌ No                     |
| `"x"`  | Create only             | ❌ Must not exist | ✅ Yes         | ❌ No                     |
| `"r+"` | Read and write          | ✅ Yes            | ❌ No          | ❌ No                     |
| `"w+"` | Read and write          | ❌ No             | ✅ Yes         | ✅ Yes                    |
| `"a+"` | Read and append         | ❌ No             | ✅ Yes         | ❌ No                     |
| `"x+"` | Create, read, and write | ❌ Must not exist | ✅ Yes         | ❌ No                     |

In [ ]:
my_file = open('test.txt','w+')

In [ ]:
my_file.write('This is a new first line\n')

25

In [ ]:
my_file = open('test.txt','a+')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
my_file.write('\nThis line is being appended to test.txt')

40

In [ ]:
%%writefile -a test.txt
This is more text being appended to test.txt
And another line here.

Appending to test.txt

In [ ]:
with open('test.txt','r') as txt:
    first_line = txt.readlines()[0]

    print(first_line)

This is a new first lineThis is more text being appended to test.txt

In [ ]:
with open('test.txt','r') as txt:
    for line in txt:
        print(line, end='')  # the end='' argument removes extra linebreaks

This is a new first lineThis is more text being appended to test.txt
And another line here.

This line is being appended to test.txtThis is a new first line
This is more text being appended to test.txt
And another line here.

In [ ]:
import pandas as pd
data = pd.read_csv('01.csv' , skiprows = 2)
data.head(20)

,Data Import Template,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44
0,Table:,Ad List,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Please do not change the template headings.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,First data column must be blank.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"If you are uploading new records, leave the ""n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,"If you are uploading new records, ""Naming Seri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Only mandatory fields are necessary for new re...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,"For updating, you can update only selective co...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,You can only upload upto 5000 records in one g...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,DocType:,Ad List,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Column Labels:,ID,AD_ID,NaN,Creator,Not Suitable,AD_NAME,LIST_ELEMENT_ID,Level3 AD,Subsidary Menu ID,...,EDUCATION_LOW,EDUCATION_MEDIUM,EDUCATION_HIGH,CONSERVATIVE,NON CONSERVATIVE,AD_LANGUAGE,AD_LANGUAGE_ID,AD_TYPE,CREATION_DATE,LAST_UPDATE_DATE
14,Column Name:,name,ad_id,attach_image_1,creator,not_suitable,ad_name,list_element_id,level3_ad,subsidary_menu_id,...,education_low,education_medium,education_high,conservative,non_conservative,ad_language,ad_language_id,ad_type,creation_date,last_update_date
15,Mandatory:,Yes,Yes,No,No,No,No,No,No,No,...,No,No,No,No,No,No,No,No,No,No
16,Type:,Data,Data,Attach Image,Link,Check,Data,Link,Data,Int,...,Check,Check,Check,Check,Check,Link,Int,Data,Date,Date
17,Info:,NaN,NaN,NaN,Valid User,0 or 1,NaN,Valid Level3 Menu,NaN,Integer,...,0 or 1,0 or 1,0 or 1,0 or 1,0 or 1,Valid Ad Language,Integer,NaN,dd-mm-yyyy,dd-mm-yyyy
18,Start entering data below this line,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,"""0663""",0663,/files/427.jpg,mohamed.ahmed@egdirection.com,0,ManLook,105,Hand sanitizer,23,...,0,1,1,1,1,1-Arabic,1,1,NaN,NaN

In [ ]:
data = pd.read_excel('02.xlsx' , skiprows = 2)
data.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Notes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Please do not change the template headings.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,First data column must be blank.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"If you are uploading new records, leave the ""n...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
outfile = open('03.csv', 'w')
outfile.write('a')
outfile.close()

In [ ]:
outfile = open('04.xls', 'w')
outfile.write('a')
outfile.close()

In [ ]:
f= open('5.txt','w') #write
f.write('write this line in the file')
f.close()

In [ ]:
f= open('5.txt','r') #read
for a in f:
    print(a)

write this line in the file

In [ ]:
f= open('5.txt','a') #append
f.write('\nmore lines')
f.close()

In [ ]:
f= open('5.txt','r') #read
for a in f:
    print(a)

write this line in the file

more lines

In [ ]:
import numpy as np
data = pd.DataFrame(np.random.randn(10000,5),columns=['1','2','3','4','5'])
print(data.head(20))
data.drop('1',axis=1,inplace=True)
print(data.head(20))

           1         2         3         4         5
0   0.810096  1.001276 -1.059602 -0.287800 -0.294200
1  -0.236408 -0.174503  0.607217 -1.464014 -1.943537
2  -0.272216 -0.174807  0.331845 -0.101612 -1.236498
3   1.524882 -1.056188  0.173758  0.750234 -1.307850
4  -0.012785 -1.286826  1.713538 -1.323596 -0.055508
5  -1.470715 -0.293724 -0.707669 -1.180544  1.191737
6  -0.556304 -0.406349  2.847975  1.161871 -0.655091
7   0.298420  2.646961 -1.349556  0.834267 -0.152442
8  -0.282514 -0.397635  0.206606 -0.805859 -0.285063
9   0.289076  1.104039  0.599614  0.839394 -1.112861
10 -0.946853 -1.640353  0.908259  2.087232  0.191398
11 -0.779695  2.031923 -0.197731 -0.908199  0.379104
12  1.181343 -0.651501 -0.631675 -0.048191 -1.420882
13 -0.170439  1.589095  0.080996  0.788757  1.283274
14  0.304072 -0.293496 -0.305879 -0.907753  2.228410
15 -0.584488 -0.647932  0.383039  0.928279 -0.568047
16 -1.801151 -0.802654 -0.373249 -1.215914  0.642304
17  0.890196 -0.915728 -0.458111  1.385926  1.923530
18  0.273810  0.619472  2.170014  0.027696 -0.447682
19 -0.418877  2.072556 -0.771728  1.461322 -0.188886
           2         3         4         5
0   1.001276 -1.059602 -0.287800 -0.294200
1  -0.174503  0.607217 -1.464014 -1.943537
2  -0.174807  0.331845 -0.101612 -1.236498
3  -1.056188  0.173758  0.750234 -1.307850
4  -1.286826  1.713538 -1.323596 -0.055508
5  -0.293724 -0.707669 -1.180544  1.191737
6  -0.406349  2.847975  1.161871 -0.655091
7   2.646961 -1.349556  0.834267 -0.152442
8  -0.397635  0.206606 -0.805859 -0.285063
9   1.104039  0.599614  0.839394 -1.112861
10 -1.640353  0.908259  2.087232  0.191398
11  2.031923 -0.197731 -0.908199  0.379104
12 -0.651501 -0.631675 -0.048191 -1.420882
13  1.589095  0.080996  0.788757  1.283274
14 -0.293496 -0.305879 -0.907753  2.228410
15 -0.647932  0.383039  0.928279 -0.568047
16 -0.802654 -0.373249 -1.215914  0.642304
17 -0.915728 -0.458111  1.385926  1.923530
18  0.619472  2.170014  0.027696 -0.447682
19  2.072556 -0.771728  1.461322 -0.188886

In [ ]:
data.to_csv('6.csv')

In [ ]:
with open('me.txt','w+') as f:

    f.write('hello world')
    f.write('\nthis is a new line')
    f.write('\nand another line')
    f.seek(0)
    print(f.read())

with open('me.txt','r') as f:
    print(f.readlines())

hello world
this is a new line
and another line
['hello world\n', 'this is a new line\n', 'and another line']

In [ ]:
f= open('7.txt','w', encoding="utf8")
f.write('سطور باللغة العربية')
f.close()

In [ ]:
f= open('7.txt','a', encoding="utf8")
f.write('\nسطر ثاني')
f.write('\nسطر ثالث')
f.write('\nسطر رابع')
f.write('\nسطر أخير')
f.close()

In [ ]:
f= open('7.txt','r', encoding="utf8")
for a in f:
    print(a)